/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FedralAdmin;

import Business.EcoSystem;
import Business.City.City;
import Business.State.State;
import Business.City.City;
import Business.Corporation.Enterprise;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Guest
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel displayPanel;
    EcoSystem system;
    Enterprise enterprise;

    public SystemAdminWorkAreaJPanel(JPanel displayPanel, EcoSystem system, Enterprise enterprise) {
        initComponents();
        this.displayPanel = displayPanel;
        this.system = system;
        this.enterprise = enterprise;
        populateTree();

    }

    public void populateTree() {
        DefaultTreeModel model = (DefaultTreeModel) jTree.getModel();

        ArrayList<State> stateList = system.getStateList();

        //debugging stateList
        for (State state : stateList) {

            System.out.println("State:" + state.getName());
        }
        ArrayList<City> cityList;
        ArrayList<Enterprise> enterpriseList;

        State state;
        City city;
        Enterprise enterprise;

        // DefaultMutableTreeNode states=new DefaultMutableTreeNode("States");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren();
        root.setUserObject("U.S.A");
        //  model.nodeChanged(root);
        // root.insert(states,0);

        DefaultMutableTreeNode stateNode;
        DefaultMutableTreeNode cityNode;
        DefaultMutableTreeNode enterpriseNode;

        for (int i = 0; i < stateList.size(); i++) {
            state = stateList.get(i);
            stateNode = new DefaultMutableTreeNode(state.getName());
            System.out.println("State added" + state);

            root.insert(stateNode, i);

            cityList = state.getCityDirectory().getCityList();
            for (int j = 0; j < cityList.size(); j++) {
                city = cityList.get(j);
                cityNode = new DefaultMutableTreeNode(city.getName());
                stateNode.insert(cityNode, j);

                enterpriseList = city.getEnterpriseDirectory().getEnterpriseList();

                for (int k = 0; k < enterpriseList.size(); k++) {
                    enterprise = enterpriseList.get(k);
                    enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                    cityNode.insert(enterpriseNode, k);

                }

            }

        }
        model.reload();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        manageadminsBtn = new javax.swing.JButton();
        guidelinesBtn = new javax.swing.JButton();
        statesBtn = new javax.swing.JButton();
        citiesBtn = new javax.swing.JButton();
        reportsBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jTree.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN WORK AREA");

        manageadminsBtn.setBackground(new java.awt.Color(255, 255, 255));
        manageadminsBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        manageadminsBtn.setText("MANAGE CITY ADMIN");
        manageadminsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageadminsBtnActionPerformed(evt);
            }
        });

        guidelinesBtn.setBackground(new java.awt.Color(255, 255, 255));
        guidelinesBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        guidelinesBtn.setText("SET GUIDELINES");
        guidelinesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guidelinesBtnActionPerformed(evt);
            }
        });

        statesBtn.setBackground(new java.awt.Color(255, 255, 255));
        statesBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        statesBtn.setText("MANAGE STATES");
        statesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statesBtnActionPerformed(evt);
            }
        });

        citiesBtn.setBackground(new java.awt.Color(255, 255, 255));
        citiesBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        citiesBtn.setText("MANAGE CITIES");
        citiesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citiesBtnActionPerformed(evt);
            }
        });

        reportsBtn.setBackground(new java.awt.Color(255, 255, 255));
        reportsBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        reportsBtn.setText("CREATE REPORTS");
        reportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(662, 662, 662)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(citiesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageadminsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(guidelinesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(statesBtn)
                .addGap(55, 55, 55)
                .addComponent(citiesBtn)
                .addGap(56, 56, 56)
                .addComponent(manageadminsBtn)
                .addGap(56, 56, 56)
                .addComponent(reportsBtn)
                .addGap(50, 50, 50)
                .addComponent(guidelinesBtn)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageadminsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageadminsBtnActionPerformed
        ManageCityAdminJPanel panel = new ManageCityAdminJPanel(displayPanel, system, enterprise);
        displayPanel.add("ManageCityAdminJPanel", panel);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.next(displayPanel);   // TODO add your handling code here:
    }//GEN-LAST:event_manageadminsBtnActionPerformed

    private void guidelinesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guidelinesBtnActionPerformed
        SetGuidelinesPanel panel = new SetGuidelinesPanel(displayPanel, system);
        displayPanel.add("SetGuidelinesPanel", panel);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.next(displayPanel);         // TODO add your handling code here:
    }//GEN-LAST:event_guidelinesBtnActionPerformed

    private void statesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statesBtnActionPerformed
        ManageStateJPanel panel = new ManageStateJPanel(displayPanel, system);
        displayPanel.add("ManageStateJPanel", panel);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.next(displayPanel); // TODO add your handling code here:
    }//GEN-LAST:event_statesBtnActionPerformed

    private void citiesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citiesBtnActionPerformed
        ManageCityJPanel panel = new ManageCityJPanel(displayPanel, system);
        displayPanel.add("ManageCityJPanel", panel);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.next(displayPanel);        // TODO add your handling code here:
    }//GEN-LAST:event_citiesBtnActionPerformed

    private void reportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsBtnActionPerformed
        ReportsJPanel panel = new ReportsJPanel(displayPanel, system);
        displayPanel.add("ReportsJPanel", panel);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.next(displayPanel);        // TODO add your handling code here:
    }//GEN-LAST:event_reportsBtnActionPerformed

    private void jTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeMouseClicked
        // TODO add your handling code here:
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTree.getLastSelectedPathComponent();
        if (node != null) {
            system.setTreeSelection(node.toString());
        }
    }//GEN-LAST:event_jTreeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton citiesBtn;
    private javax.swing.JButton guidelinesBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree;
    private javax.swing.JButton manageadminsBtn;
    private javax.swing.JButton reportsBtn;
    private javax.swing.JButton statesBtn;
    // End of variables declaration//GEN-END:variables
}
