/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CityAdmin;

import Business.City.City;
import Business.Corporation.Enterprise;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author lahar
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel displayPanel;
    City city;
    EcoSystem system;
    UserAccount userAccount;
    Enterprise enterprise;

    /**
     * Creates new form AdminWorkAreaPanel
     */
    public AdminWorkAreaJPanel(JPanel displayPanel, City city, EcoSystem system, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.displayPanel = displayPanel;
        this.city = city;
        this.system = system;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        citylabel.setText(city.getName());
        typelabel.setText(userAccount.geteType().getValue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        citylabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        typelabel = new javax.swing.JLabel();
        manageusersBtn = new javax.swing.JButton();
        workRequestsBtn = new javax.swing.JButton();
        generateBillsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN WORK AREA");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CITY");
        jLabel3.setToolTipText("");

        citylabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        citylabel.setForeground(new java.awt.Color(255, 255, 255));
        citylabel.setText("<value>");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TYPE");
        jLabel4.setToolTipText("");

        typelabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        typelabel.setForeground(new java.awt.Color(255, 255, 255));
        typelabel.setText("<value>");

        manageusersBtn.setBackground(new java.awt.Color(255, 255, 255));
        manageusersBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        manageusersBtn.setText("MANAGE USERS");
        manageusersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageusersBtnActionPerformed(evt);
            }
        });

        workRequestsBtn.setBackground(new java.awt.Color(255, 255, 255));
        workRequestsBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        workRequestsBtn.setText("WORK REQUESTS");
        workRequestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workRequestsBtnActionPerformed(evt);
            }
        });

        generateBillsBtn.setBackground(new java.awt.Color(255, 255, 255));
        generateBillsBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        generateBillsBtn.setText("GENERATE BILLS");
        generateBillsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBillsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(538, 538, 538)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(citylabel, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(typelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(712, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generateBillsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(workRequestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageusersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(847, 847, 847))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(756, 756, 756))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(citylabel))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(typelabel))
                .addGap(32, 32, 32)
                .addComponent(manageusersBtn)
                .addGap(91, 91, 91)
                .addComponent(workRequestsBtn)
                .addGap(90, 90, 90)
                .addComponent(generateBillsBtn)
                .addContainerGap(297, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageusersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageusersBtnActionPerformed
        ManageUsersPanel panel = new ManageUsersPanel(displayPanel, system, userAccount, city);
        displayPanel.add("ManageUsersPanel", panel);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.next(displayPanel);          // TODO add your handling code here:
    }//GEN-LAST:event_manageusersBtnActionPerformed

    private void workRequestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workRequestsBtnActionPerformed
        WorkRequestPanel panel = new WorkRequestPanel(displayPanel, system, userAccount, enterprise, city);
        displayPanel.add("WorkRequestPanel", panel);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.next(displayPanel);  // TODO add your handling code here:
    }//GEN-LAST:event_workRequestsBtnActionPerformed

    private void generateBillsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBillsBtnActionPerformed
        GenerateBillsPanel panel = new GenerateBillsPanel(displayPanel, system, city, userAccount);
        displayPanel.add("GenerateBillsPanel", panel);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.next(displayPanel);   // TODO add your handling code here:
    }//GEN-LAST:event_generateBillsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel citylabel;
    private javax.swing.JButton generateBillsBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton manageusersBtn;
    private javax.swing.JLabel typelabel;
    private javax.swing.JButton workRequestsBtn;
    // End of variables declaration//GEN-END:variables
}
