/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CityAdmin;

import Business.City.City;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BillRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lahar
 */
public class GenerateBillsPanel extends javax.swing.JPanel {

    private JPanel displayPanel;
    private EcoSystem system;
    private City city;
    private UserAccount userAccount;
    private boolean flag1;

    /**
     * Creates new form GenerateBillsPanel
     */
    GenerateBillsPanel(JPanel displayPanel, EcoSystem system, City city, UserAccount userAccount) {
        initComponents();
        this.displayPanel = displayPanel;
        this.system = system;//To change body of generated methods, choose Tools | Templates.
        this.city = city;
        this.userAccount = userAccount;

        populateBillingTable();

    }

    private void populateBillingTable() {
        DefaultTableModel model = (DefaultTableModel) billingTable.getModel();

        model.setRowCount(0);
        for (UserAccount userAccount : system.getUserAccountDirectory().getUserAccountList()) {
            Object[] row = new Object[4];
            row[0] = userAccount;
            row[1] = userAccount.getUsername();
            row[2] = userAccount.getStreet1();
            row[3] = userAccount.getBillingStatus();

            if (city.getName().equalsIgnoreCase(userAccount.getCity())) {
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        billingTable = new javax.swing.JTable();
        billBtn = new javax.swing.JButton();
        notificationBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GENERATE BILLS");

        billingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "ADDRESS", "STATUS"
            }
        ));
        jScrollPane2.setViewportView(billingTable);

        billBtn.setBackground(new java.awt.Color(255, 255, 255));
        billBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        billBtn.setText("GENERATE BILL");
        billBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billBtnActionPerformed(evt);
            }
        });

        notificationBtn.setBackground(new java.awt.Color(255, 255, 255));
        notificationBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        notificationBtn.setText("SEND NOTIFICATION");
        notificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backBtn.setText(">>BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(666, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(530, 530, 530))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(billBtn)
                        .addGap(108, 108, 108)
                        .addComponent(notificationBtn)
                        .addGap(594, 594, 594))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(742, 742, 742))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billBtn)
                    .addComponent(notificationBtn))
                .addContainerGap(347, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void billBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billBtnActionPerformed

        int selectedrow = billingTable.getSelectedRow();

        if (selectedrow >= 0) {
            UserAccount ua = (UserAccount) billingTable.getValueAt(selectedrow, 0);

            BillRequest request = new BillRequest();

            request.setMessage("Your bill is due");
            request.setBillingStatus("Pending");
            ua.setBillingStatus("Pending");
            request.setBillType(userAccount.geteType().getValue());
            request.setFlag(false);

            ua.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Bill Generated successfully");
        } else {
            JOptionPane.showMessageDialog(null, "Please select any row");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_billBtnActionPerformed

    private void notificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationBtnActionPerformed

        int selectedrow = billingTable.getSelectedRow();

        if (selectedrow >= 0) {
            UserAccount ua = (UserAccount) billingTable.getValueAt(selectedrow, 0);

            BillRequest request = new BillRequest();

            request.setFlag(true);
            ua.setNotify(true);

            if (ua.getBillingStatus().equalsIgnoreCase("Paid")) {
                flag1 = true;
            }

            ua.getWorkQueue().getWorkRequestList().add(request);

            if (flag1 == false) {
                JOptionPane.showMessageDialog(null, "User Notified successfully");
            } else {
                JOptionPane.showMessageDialog(null, "User Already paid the bill");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select any row");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_notificationBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        displayPanel.remove(this);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.previous(displayPanel);        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton billBtn;
    private javax.swing.JTable billingTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton notificationBtn;
    // End of variables declaration//GEN-END:variables
}
