/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserAccount;

import Business.CorporationAdmin.Meter;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.CorporationAdmin.Usage;
import java.awt.CardLayout;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lahar
 */
public class ManageAppliancesPanel extends javax.swing.JPanel implements Observer {

    private JPanel displayPanel;
    private EcoSystem system;
    private UserAccount userAccount;
    private Meter meter;

    /**
     * Creates new form ManageAppliancesPanel
     */
    ManageAppliancesPanel(JPanel displayPanel, EcoSystem system, UserAccount userAccount) {
        initComponents();
        this.displayPanel = displayPanel;
        this.system = system;//To change body of generated methods, choose Tools | Templates.
        this.userAccount = userAccount;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ac1on = new javax.swing.JRadioButton();
        ac2Off = new javax.swing.JRadioButton();
        ac2on = new javax.swing.JRadioButton();
        rad2on = new javax.swing.JRadioButton();
        ovenOn = new javax.swing.JRadioButton();
        washingmacon = new javax.swing.JRadioButton();
        rad1on = new javax.swing.JRadioButton();
        ac1Off = new javax.swing.JRadioButton();
        rad1Off = new javax.swing.JRadioButton();
        rad2Off = new javax.swing.JRadioButton();
        washingmachineOff = new javax.swing.JRadioButton();
        ovenOff = new javax.swing.JRadioButton();
        backBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ac1Txt = new javax.swing.JTextField();
        ac2Txt = new javax.swing.JTextField();
        rad2Txt = new javax.swing.JTextField();
        rad1Txt = new javax.swing.JTextField();
        ovenTxt = new javax.swing.JTextField();
        wmTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        statusTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MANAGE APPLIANCES");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RADIATOR-2");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AC-1");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RADIATOR-1");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("AC-2");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MICRO-OVEN");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("WASHING MACHINE");
        jLabel8.setToolTipText("");

        ac1on.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ac1on.setForeground(new java.awt.Color(255, 255, 255));
        ac1on.setText("ON");
        ac1on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac1onActionPerformed(evt);
            }
        });

        ac2Off.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ac2Off.setForeground(new java.awt.Color(255, 255, 255));
        ac2Off.setText("OFF");
        ac2Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac2OffActionPerformed(evt);
            }
        });

        ac2on.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ac2on.setForeground(new java.awt.Color(255, 255, 255));
        ac2on.setText("ON");
        ac2on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac2onActionPerformed(evt);
            }
        });

        rad2on.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rad2on.setForeground(new java.awt.Color(255, 255, 255));
        rad2on.setText("ON");
        rad2on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad2onActionPerformed(evt);
            }
        });

        ovenOn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ovenOn.setForeground(new java.awt.Color(255, 255, 255));
        ovenOn.setText("ON");
        ovenOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovenOnActionPerformed(evt);
            }
        });

        washingmacon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        washingmacon.setForeground(new java.awt.Color(255, 255, 255));
        washingmacon.setText("ON");
        washingmacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                washingmaconActionPerformed(evt);
            }
        });

        rad1on.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rad1on.setForeground(new java.awt.Color(255, 255, 255));
        rad1on.setText("ON");
        rad1on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad1onActionPerformed(evt);
            }
        });

        ac1Off.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ac1Off.setForeground(new java.awt.Color(255, 255, 255));
        ac1Off.setText("OFF");
        ac1Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac1OffActionPerformed(evt);
            }
        });

        rad1Off.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rad1Off.setForeground(new java.awt.Color(255, 255, 255));
        rad1Off.setText("OFF");
        rad1Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad1OffActionPerformed(evt);
            }
        });

        rad2Off.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rad2Off.setForeground(new java.awt.Color(255, 255, 255));
        rad2Off.setText("OFF");
        rad2Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad2OffActionPerformed(evt);
            }
        });

        washingmachineOff.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        washingmachineOff.setForeground(new java.awt.Color(255, 255, 255));
        washingmachineOff.setText("OFF");
        washingmachineOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                washingmachineOffActionPerformed(evt);
            }
        });

        ovenOff.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ovenOff.setForeground(new java.awt.Color(255, 255, 255));
        ovenOff.setText("OFF");
        ovenOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovenOffActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backBtn.setText(">>BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("STATUS");
        jLabel9.setToolTipText("");

        ac1Txt.setEditable(false);
        ac1Txt.setBackground(new java.awt.Color(255, 255, 255));
        ac1Txt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ac1Txt.setEnabled(false);

        ac2Txt.setEditable(false);
        ac2Txt.setBackground(new java.awt.Color(255, 255, 255));
        ac2Txt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ac2Txt.setEnabled(false);

        rad2Txt.setEditable(false);
        rad2Txt.setBackground(new java.awt.Color(255, 255, 255));
        rad2Txt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rad2Txt.setEnabled(false);
        rad2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad2TxtActionPerformed(evt);
            }
        });

        rad1Txt.setEditable(false);
        rad1Txt.setBackground(new java.awt.Color(255, 255, 255));
        rad1Txt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rad1Txt.setEnabled(false);

        ovenTxt.setEditable(false);
        ovenTxt.setBackground(new java.awt.Color(255, 255, 255));
        ovenTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ovenTxt.setEnabled(false);

        wmTxt.setEditable(false);
        wmTxt.setBackground(new java.awt.Color(255, 255, 255));
        wmTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        wmTxt.setEnabled(false);
        wmTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wmTxtActionPerformed(evt);
            }
        });

        statusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Meter Reading", "Over Usage", "Status"
            }
        ));
        jScrollPane2.setViewportView(statusTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(645, 645, 645)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(202, 202, 202)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ac2on, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac1on, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ac1Off, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac2Off, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addGap(65, 65, 65))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(125, 125, 125)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ovenOn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(washingmacon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rad1on, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rad2on, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rad2Off, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rad1Off, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(washingmachineOff, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ovenOff, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(745, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 1168, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rad1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rad2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ovenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ac2Txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac1Txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(453, 453, 453))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(539, 539, 539))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(589, 589, 589))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(799, 799, 799))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ac1on)
                            .addComponent(ac1Off)
                            .addComponent(ac1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ac2on)
                            .addComponent(ac2Off)
                            .addComponent(ac2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rad1on)
                    .addComponent(rad1Off)
                    .addComponent(rad1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rad2on)
                    .addComponent(rad2Off)
                    .addComponent(rad2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(washingmacon)
                    .addComponent(washingmachineOff)
                    .addComponent(wmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ovenOn)
                    .addComponent(ovenOff)
                    .addComponent(ovenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(backBtn)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) statusTable.getModel();

        model.setRowCount(0);

        Object[] row = new Object[3];

        for (Meter meter1 : userAccount.getMeterReadingList()) {
            this.meter = meter1;
        }

        double reading = this.meter.getEmReading() + userAccount.getUsage().getUsage() + userAccount.getUsage().getOver_usage();
        row[0] = reading;
        row[1] = userAccount.getUsage().getOver_usage();
        if (userAccount.getUsage().getF2() == 0) {
            row[2] = "Normal";
        } else if (userAccount.getUsage().getF2() == 1) {
            row[2] = "Overload";

        }
        model.addRow(row);

    }
    private void ac2onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac2onActionPerformed
        userAccount.getAppliance().setAc2(true);
        if (ac2on.isSelected()) {
            ac2Off.setSelected(false);
            ac2Txt.setText(ac2on.getText());
        } // TODO add your handling code here:
    }//GEN-LAST:event_ac2onActionPerformed

    private void rad2onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad2onActionPerformed
        userAccount.getAppliance().setRad2(true);
        if (rad2on.isSelected()) {
            rad2Off.setSelected(false);
            rad2Txt.setText(rad2on.getText());
        } // TODO add your handling code here:
    }//GEN-LAST:event_rad2onActionPerformed

    private void ovenOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovenOnActionPerformed
        userAccount.getAppliance().setMwo(true);
        if (ovenOn.isSelected()) {
            ovenOff.setSelected(false);
            ovenTxt.setText(ovenOn.getText());
        }  // TODO add your handling code here:
    }//GEN-LAST:event_ovenOnActionPerformed

    private void washingmaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_washingmaconActionPerformed
        userAccount.getAppliance().setWm(true);
        if (washingmacon.isSelected()) {
            washingmachineOff.setSelected(false);
            wmTxt.setText(washingmacon.getText());
        }// TODO add your handling code here:
    }//GEN-LAST:event_washingmaconActionPerformed

    private void rad1onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad1onActionPerformed
        userAccount.getAppliance().setRad1(true);
        if (rad1on.isSelected()) {
            rad1Off.setSelected(false);
            rad1Txt.setText(rad1on.getText());
        }// TODO add your handling code here:
    }//GEN-LAST:event_rad1onActionPerformed

    private void rad1OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad1OffActionPerformed
        userAccount.getAppliance().setRad1(false);
        if (rad1Off.isSelected()) {
            rad1on.setSelected(false);
            rad1Txt.setText(rad1Off.getText());
        } // TODO add your handling code here:
    }//GEN-LAST:event_rad1OffActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userAccount.getUsage().setF1(1);
        displayPanel.remove(this);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.previous(displayPanel);         // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void wmTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wmTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wmTxtActionPerformed

    private void rad2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad2TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad2TxtActionPerformed

    private void ac1onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac1onActionPerformed
        userAccount.getAppliance().setAc1(true);
        if (ac1on.isSelected()) {
            ac1Off.setSelected(false);
            ac1Txt.setText(ac1on.getText());
        }// TODO add your handling code here:
    }//GEN-LAST:event_ac1onActionPerformed

    private void ac1OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac1OffActionPerformed
        userAccount.getAppliance().setAc1(false);
        if (ac1Off.isSelected()) {
            ac1on.setSelected(false);
            ac1Txt.setText(ac1Off.getText());
        }  // TODO add your handling code here:
    }//GEN-LAST:event_ac1OffActionPerformed

    private void ac2OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac2OffActionPerformed
        userAccount.getAppliance().setAc2(false);
        if (ac2Off.isSelected()) {
            ac2on.setSelected(false);
            ac2Txt.setText(ac2Off.getText());
        }  // TODO add your handling code here:
    }//GEN-LAST:event_ac2OffActionPerformed

    private void rad2OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad2OffActionPerformed
        userAccount.getAppliance().setRad2(false);
        if (rad2Off.isSelected()) {
            rad2on.setSelected(false);
            rad2Txt.setText(rad2Off.getText());
        } // TODO add your handling code here:
    }//GEN-LAST:event_rad2OffActionPerformed

    private void washingmachineOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_washingmachineOffActionPerformed
        userAccount.getAppliance().setWm(false);
        if (washingmachineOff.isSelected()) {
            washingmacon.setSelected(false);
            wmTxt.setText(washingmachineOff.getText());
        }   // TODO add your handling code here:
    }//GEN-LAST:event_washingmachineOffActionPerformed

    private void ovenOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovenOffActionPerformed
        userAccount.getAppliance().setMwo(false);
        if (ovenOff.isSelected()) {
            ovenOn.setSelected(false);
            ovenTxt.setText(ovenOff.getText());
        }   // TODO add your handling code here:
    }//GEN-LAST:event_ovenOffActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ac1Off;
    private javax.swing.JTextField ac1Txt;
    private javax.swing.JRadioButton ac1on;
    private javax.swing.JRadioButton ac2Off;
    private javax.swing.JTextField ac2Txt;
    private javax.swing.JRadioButton ac2on;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton ovenOff;
    private javax.swing.JRadioButton ovenOn;
    private javax.swing.JTextField ovenTxt;
    private javax.swing.JRadioButton rad1Off;
    private javax.swing.JTextField rad1Txt;
    private javax.swing.JRadioButton rad1on;
    private javax.swing.JRadioButton rad2Off;
    private javax.swing.JTextField rad2Txt;
    private javax.swing.JRadioButton rad2on;
    private javax.swing.JTable statusTable;
    private javax.swing.JRadioButton washingmachineOff;
    private javax.swing.JRadioButton washingmacon;
    private javax.swing.JTextField wmTxt;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (o instanceof Usage) {
            populateTable();
        }
    }

}
