/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserAccount;

import Business.City.City;
import Business.CorporationAdmin.Usage;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lahar
 */
public class UsersMainPagePanel extends javax.swing.JPanel {

    private EcoSystem system;
    private JPanel displayPanel;
    private City city;
    private UserAccount userAccount;

    /**
     * Creates new form UsersMainPagePanel
     */
    public UsersMainPagePanel(JPanel displayPanel, City city, EcoSystem system, UserAccount userAccount) {
        initComponents();
        this.displayPanel = displayPanel;
        this.city = city;
        this.userAccount = userAccount;
        this.system = system; //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        manageAppliancesBtn = new javax.swing.JButton();
        billBtn = new javax.swing.JButton();
        requestsBtn = new javax.swing.JButton();
        viewDataBtn = new javax.swing.JButton();
        currentStatusBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EGW SYSTEM");

        manageAppliancesBtn.setBackground(new java.awt.Color(255, 255, 255));
        manageAppliancesBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        manageAppliancesBtn.setText("MANAGE APPLIANCES");
        manageAppliancesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAppliancesBtnActionPerformed(evt);
            }
        });

        billBtn.setBackground(new java.awt.Color(255, 255, 255));
        billBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        billBtn.setText("BILL PAYMENTS");
        billBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billBtnActionPerformed(evt);
            }
        });

        requestsBtn.setBackground(new java.awt.Color(255, 255, 255));
        requestsBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        requestsBtn.setText("REQUESTS");
        requestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestsBtnActionPerformed(evt);
            }
        });

        viewDataBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewDataBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewDataBtn.setText("VIEW DATA");
        viewDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDataBtnActionPerformed(evt);
            }
        });

        currentStatusBtn.setBackground(new java.awt.Color(255, 255, 255));
        currentStatusBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        currentStatusBtn.setText("CURRENT STATUS");
        currentStatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentStatusBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(763, 763, 763)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageAppliancesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentStatusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(762, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(776, 776, 776))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(manageAppliancesBtn)
                .addGap(59, 59, 59)
                .addComponent(requestsBtn)
                .addGap(60, 60, 60)
                .addComponent(viewDataBtn)
                .addGap(65, 65, 65)
                .addComponent(currentStatusBtn)
                .addGap(58, 58, 58)
                .addComponent(billBtn)
                .addContainerGap(246, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageAppliancesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAppliancesBtnActionPerformed

        Usage usage = userAccount.getUsage();
        Thread t = new Thread(usage);
        t.start();
        ManageAppliancesPanel panel = new ManageAppliancesPanel(displayPanel, system, userAccount);

        usage.addObserver(panel);

        //   ManageAppliancesPanel panel=new ManageAppliancesPanel(displayPanel,system );  
        displayPanel.add("ManageAppliancesPanel", panel);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.next(displayPanel);  // TODO add your handling code here:
    }//GEN-LAST:event_manageAppliancesBtnActionPerformed

    private void billBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billBtnActionPerformed
        if (!userAccount.getBillingStatus().equalsIgnoreCase("paid") && userAccount.isNotify()) {
            JOptionPane.showMessageDialog(null, "Your Bill is past due date please pay ASAP to avoid disconnection");
        }
        BillPaymentsPanel panel = new BillPaymentsPanel(displayPanel, system, userAccount);
        displayPanel.add("BillPaymentsPanel", panel);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.next(displayPanel); // TODO add your handling code here:
    }//GEN-LAST:event_billBtnActionPerformed

    private void requestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestsBtnActionPerformed
        RequestsPanel panel = new RequestsPanel(displayPanel, system, userAccount);
        displayPanel.add("RequestsPanel", panel);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.next(displayPanel); // TODO add your handling code here:
    }//GEN-LAST:event_requestsBtnActionPerformed

    private void viewDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDataBtnActionPerformed
        ViewDataPanel panel = new ViewDataPanel(displayPanel, system, userAccount);
        displayPanel.add("ViewDataPanel", panel);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.next(displayPanel); // TODO add your handling code here:
    }//GEN-LAST:event_viewDataBtnActionPerformed

    private void currentStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentStatusBtnActionPerformed
        CurrentStatusPanel panel = new CurrentStatusPanel(displayPanel, system, userAccount);
        displayPanel.add("CurrentStatusPanel", panel);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.next(displayPanel); // TODO add your handling code here:
    }//GEN-LAST:event_currentStatusBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billBtn;
    private javax.swing.JButton currentStatusBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageAppliancesBtn;
    private javax.swing.JButton requestsBtn;
    private javax.swing.JButton viewDataBtn;
    // End of variables declaration//GEN-END:variables
}
