/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserAccount;

import Business.CorporationAdmin.Bill;
import Business.CorporationAdmin.Meter;
import Business.EcoSystem;
import Business.Threshold;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lahar
 */
public class ViewDataPanel extends javax.swing.JPanel {

    private JPanel displayPanel;
    private EcoSystem system;
    private UserAccount userAccount;
    private Meter meterFrom;
    private Meter meterTo;

    /**
     * Creates new form ViewDataPanel
     */
    ViewDataPanel(JPanel displayPanel, EcoSystem system, UserAccount userAccount) {
        initComponents();
        this.displayPanel = displayPanel;
        this.system = system;//To change body of generated methods, choose Tools | Templates.
        this.userAccount = userAccount;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        fromDate = new org.jdesktop.swingx.JXDatePicker();
        toDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        electricityUsageTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        electricityAmountTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        waterUsageTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        waterAmountTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        gasUsageTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        gasAmountTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIEW DATA");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATE");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("From");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("To");
        jLabel5.setToolTipText("");

        submitBtn.setBackground(new java.awt.Color(255, 255, 255));
        submitBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backBtn.setText(">>BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Electricity");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gas");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Water");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("USAGE");
        jLabel10.setToolTipText("");

        electricityUsageTxt.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("AMOUNT");
        jLabel11.setToolTipText("");

        electricityAmountTxt.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("USAGE");
        jLabel12.setToolTipText("");

        waterUsageTxt.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("AMOUNT");
        jLabel13.setToolTipText("");

        waterAmountTxt.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("USAGE");
        jLabel14.setToolTipText("");

        gasUsageTxt.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("AMOUNT");
        jLabel15.setToolTipText("");

        gasAmountTxt.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(backBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(electricityUsageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(electricityAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gasUsageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(gasAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(369, 369, 369)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(674, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(202, 202, 202)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)))
                .addGap(275, 275, 275)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(waterUsageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(waterAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12))
                .addGap(421, 421, 421))
            .addGroup(layout.createSequentialGroup()
                .addGap(859, 859, 859)
                .addComponent(submitBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(electricityUsageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(electricityAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(submitBtn)
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(waterUsageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(waterAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gasUsageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gasAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        int from = 0;
        int to = 0;
        double eTotalUsage = 0, gTotalUsage = 0, wTotalUsage = 0;
        double ebill1 = 0, ebill2 = 0, ebill3 = 0, ebill4 = 0, eBill, gBill, wBill, finalEBill = 0;
        double gbill1 = 0, gbill2 = 0, gbill3 = 0, gbill4 = 0, finalGBill = 0;
        double wbill1 = 0, wbill2 = 0, wbill3 = 0, wbill4 = 0, finalWBill = 0;

//      System.out.println(fromDate.getDate().toString().substring(0, 9));
        if (fromDate.getDate() == null || toDate.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please enter Dates");
        } else {

            for (Meter meter : userAccount.getMeterReadingList()) {
                if (meter.getReadingDate().toString().substring(0, 9).equals(fromDate.getDate().toString().substring(0, 9))) {
                    // this.meterFrom=meter;
                    from = userAccount.getMeterReadingList().indexOf(meter);
                }

                if (meter.getReadingDate().toString().substring(0, 9).equals(toDate.getDate().toString().substring(0, 9))) {
                    // this.meterTo=meter;
                    to = userAccount.getMeterReadingList().indexOf(meter);
                }

            }

            for (int i = to; i <= from; i++) {
                Meter meter1 = userAccount.getMeterReadingList().get(i);

                eTotalUsage += meter1.getEmReading();
                gTotalUsage += meter1.getGmReading();
                wTotalUsage += meter1.getWmReading();

                Bill bill = new Bill();

                for (Threshold t : system.getThresholdList()) {
                    if (meter1.getEmReading() <= 30 && t.geteRange().equalsIgnoreCase("0-30")) {
                        ebill1 = t.geteFactor() * meter1.getEmReading();
                    }

                    if (meter1.getEmReading() >= 31 && meter1.getEmReading() <= 33 && t.geteRange().equalsIgnoreCase("31-33")) {
                        ebill2 = t.geteFactor() * meter1.getEmReading();
                    }

                    if (meter1.getEmReading() >= 34 && meter1.getEmReading() <= 36 && t.geteRange().equalsIgnoreCase("34-36")) {
                        ebill3 = t.geteFactor() * meter1.getEmReading();
                    }

                    if (meter1.getEmReading() >= 37 && meter1.getEmReading() <= 40 && t.geteRange().equalsIgnoreCase("37-40")) {
                        ebill4 = t.geteFactor() * meter1.getEmReading();
                    }

                }

                for (Threshold t : system.getThresholdList()) {

                    if (meter1.getGmReading() <= 5 && t.getgRange().equalsIgnoreCase("0-5")) {
                        gbill1 = t.getgFactor() * meter1.getGmReading();
                    }

                    if (meter1.getGmReading() >= 6 && meter1.getGmReading() <= 11 && t.getgRange().equalsIgnoreCase("6-11")) {
                        gbill2 = t.getgFactor() * meter1.getGmReading();
                    }

                    if (meter1.getGmReading() >= 12 && meter1.getGmReading() <= 17 && t.getgRange().equalsIgnoreCase("12-17")) {
                        gbill3 = t.getgFactor() * meter1.getGmReading();
                    }

                    if (meter1.getGmReading() >= 18 && meter1.getGmReading() <= 23 && t.getgRange().equalsIgnoreCase("18-23")) {
                        gbill4 = t.getgFactor() * meter1.getGmReading();
                    }

                }

                for (Threshold t : system.getThresholdList()) {

                    if (meter1.getWmReading() <= 3 && t.getwRange().equalsIgnoreCase("0-3")) {
                        wbill1 = t.getwFactor() * meter1.getWmReading();
                    }

                    if (meter1.getWmReading() >= 4 && meter1.getWmReading() <= 7 && t.getwRange().equalsIgnoreCase("4-7")) {
                        wbill2 = t.getwFactor() * meter1.getWmReading();
                    }

                    if (meter1.getWmReading() >= 8 && meter1.getWmReading() <= 11 && t.getwRange().equalsIgnoreCase("8-11")) {
                        wbill3 = t.getwFactor() * meter1.getWmReading();
                    }

                    if (meter1.getWmReading() >= 12 && meter1.getWmReading() <= 15 && t.getwRange().equalsIgnoreCase("12-15")) {
                        wbill4 = t.getwFactor() * meter1.getWmReading();
                    }

                }

                eBill = ebill1 + ebill2 + ebill3 + ebill4;
                gBill = gbill1 + gbill2 + gbill3 + gbill4;
                wBill = wbill1 + wbill2 + wbill3 + wbill4;

                bill.seteBill(eBill);
                bill.setgBill(gBill);
                bill.setwBill(wBill);

                userAccount.getBillList().add(bill);

            }

            for (Bill bill : userAccount.getBillList()) {
                finalEBill += bill.geteBill();
                finalGBill += bill.getgBill();
                finalWBill += bill.getwBill();
            }

//        DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
//        String szDate = oDateFormat.format(oDate);
            electricityUsageTxt.setText(String.valueOf(eTotalUsage));
            gasUsageTxt.setText(String.valueOf(gTotalUsage));
            waterUsageTxt.setText(String.valueOf(wTotalUsage));
            electricityAmountTxt.setText(String.valueOf(finalEBill));
            gasAmountTxt.setText(String.valueOf(finalGBill));
            waterAmountTxt.setText(String.valueOf(finalWBill));
        }

    }//GEN-LAST:event_submitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        displayPanel.remove(this);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.previous(displayPanel);         // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField electricityAmountTxt;
    private javax.swing.JTextField electricityUsageTxt;
    private org.jdesktop.swingx.JXDatePicker fromDate;
    private javax.swing.JTextField gasAmountTxt;
    private javax.swing.JTextField gasUsageTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton submitBtn;
    private org.jdesktop.swingx.JXDatePicker toDate;
    private javax.swing.JTextField waterAmountTxt;
    private javax.swing.JTextField waterUsageTxt;
    // End of variables declaration//GEN-END:variables
}
